### PR TITLE
Code review and cleanup for Busybox PR 

### PR DESCRIPTION
**Pull request by jvazquez-r7**
Hello @vallejocc,

This pull request tries to clean the PR you've opened on https://github.com/rapid7/metasploit-framework/pull/5722

Do you mind to review and once you agree with the changes land it? https://github.com/rapid7/metasploit-framework/pull/5722 will be automatically updated and mostly ready to go :)

Then I'd need please pcap of all the modules working. I'll review pcap's, make some extra clean ups if necessary and land it. 

Thanks very much for your initial PR and your work on it! :)

### CODE REVIEW

**Comment by vallejocc** [comment]
@jvazquez-r7 Thank you for your help :) Sorry for the late response, i have been out for some days. I am going to view the modifications and test the modules with them against some routers, and to keep pcap for sending to you.

**Comment by jvazquez-r7** [comment]
@vallejocc thank you! Really appreciated! No rush, I'll review pcap's once it's done, fix anything if necessary and land your PR into rapid7/master.

On the other hand, feel free to use this PR to comment my changes if you notice I wasted something while done some code mods :) Hopefully I didn't break nothing too hard :package: 

Thanks again!

**Comment by jvazquez-r7** [comment]
Thanks @vallejocc ! I've updated the code with your feedback. Let me know if there is something else. On the other hand, I didn't get any email from you :\ Did you send it to juan[at]metasploit.com ? or just to msfdev[at]metasploit.com? (juan[at]metasploit.com should work better :P)

Btw, once you feel comfortable with the code here, feel free to land this PR so your original https://github.com/rapid7/metasploit-framework/pull/5722 will be automatically updated :)

**Comment by vallejocc** [comment]
@jvazquez-r7 i resent the files and landed the PR. I did an additional test with the last files and it worked fine :) Thank you!

**Pull request merged**
